name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip3 install pytest pytest-ros
          
      - name: Build
        run: |
          . /opt/ros/humble/setup.sh
          mkdir -p /workspace/src
          cp -r $GITHUB_WORKSPACE /workspace/src/
          cd /workspace
          colcon build --symlink-install
          
      - name: Test
        run: |
          . /opt/ros/humble/setup.sh
          . /workspace/install/setup.sh
          cd /workspace
          colcon test
          colcon test-result --verbose